vim.g.use_nerd_font = true

local opt = vim.opt

opt.number = true
opt.relativenumber = true
opt.cursorline = true
opt.termguicolors = true
opt.signcolumn = 'yes'
opt.showmode = false
opt.laststatus = 3
opt.wrap = false
opt.splitright = true
opt.splitbelow = true
opt.ignorecase = true
opt.smartcase = true
opt.expandtab = true
opt.shiftwidth = 2
opt.tabstop = 2
opt.smartindent = true
opt.clipboard = 'unnamedplus'
opt.updatetime = 300
opt.timeoutlen = 400
opt.scrolloff = 4
opt.sidescrolloff = 8
opt.pumheight = 12
opt.completeopt = { 'menu', 'menuone', 'noselect' }
opt.swapfile = false
opt.backup = false
opt.writebackup = false
opt.undofile = true
